package br.com.alura.bolao.modelo;

public enum TipoCriterio {
	
	PE, //PLACAR EXATO
	RCG, //RESULTADO CERTO GOL - ACERTOU O VENCEDOR E UM DOS PLACARES
	RC, //RESULTADO CERTO - ACERTOU O VENCEDOR OU EMPATE, MAS COM PLACAR ERRADO
	GE, //GOL ERRADO - ACERTOU O GOL DE UM DOS TIMES MAS O VENCEDOR NÃO
	CAMPEAO,
	VICE,
	TERCEIRO,
	QUARTO,
	TIMEARTILHEIRO
	

}
